Env = dev
Port = :8099
RootDir = /mnt/www/passport
Domain = sso.com
# debug or release
RunMode = debug

[db]
Host = 127.0.0.1:3306
User = root
Passwd = root
DbName = passport
Charset = utf8mb4

[redis]
Host = 127.0.0.1:6379
Passwd =
DbNum = 5

[log]
Dir = %(RootDir)s/log