basePath: /
definitions:
  model.Client:
    properties:
      callback:
        type: string
      created_at:
        type: string
      domain:
        type: string
      id:
        type: integer
      name:
        type: string
      secret:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      gender:
        type: integer
      id:
        type: integer
      mobile:
        type: string
      realname:
        type: string
    type: object
  record.Result:
    properties:
      clientName:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      ipAddr:
        type: string
      realname:
        type: string
      userAgent:
        type: string
    type: object
  static.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: sso.com:8099
info:
  contact:
    name: wuzehui
  description: 单点登录系统api文档
  title: 单点登录系统
  version: "1.0"
paths:
  /api/v1/clients:
    get:
      description: 客户端列表
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 客户端管理
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 添加客户端
      parameters:
      - description: 回调地址
        in: formData
        name: callback
        required: true
        type: string
      - description: 域名
        in: formData
        name: domain
        required: true
        type: string
      - description: 域名
        in: formData
        name: name
        required: true
        type: string
      - description: 用来签名校验的密钥
        in: formData
        name: secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 客户端管理
  /api/v1/clients/{id}:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 客户端更新
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 回调地址
        in: formData
        name: callback
        required: true
        type: string
      - description: 域名
        in: formData
        name: domain
        required: true
        type: string
      - description: 域名
        in: formData
        name: name
        required: true
        type: string
      - description: 用来签名校验的密钥
        in: formData
        name: secret
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 客户端管理
  /api/v1/clients/{id}/toggle-status:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 客户端启用/禁用
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 客户端管理
  /api/v1/clients/check-callback:
    head:
      consumes:
      - application/x-www-form-urlencoded
      description: 检测客户端地址
      parameters:
      - description: 回调地址
        in: path
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 客户端管理
  /api/v1/records:
    get:
      description: 登录日志
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 信息查看
  /api/v1/users:
    get:
      description: 用户列表
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 添加用户
      parameters:
      - description: 用户邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 手机号
        in: formData
        name: mobile
        required: true
        type: string
      - description: 真实姓名
        in: formData
        name: realName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
  /api/v1/users/{id}:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户更新
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户邮箱
        in: formData
        name: email
        required: true
        type: string
      - description: 手机号
        in: formData
        name: mobile
        required: true
        type: string
      - description: 真实姓名
        in: formData
        name: realName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
  /api/v1/users/{id}/reset-password:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 重置密码
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 新密码
        in: formData
        maxLength: 255
        minLength: 1
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        maxLength: 255
        minLength: 1
        name: password_verify
        required: true
        type: string
      - in: formData
        maxLength: 255
        minLength: 1
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
  /api/v1/users/{id}/toggle-status:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户启用/禁用
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
  /api/v1/users/reset-password:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 重置密码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 用户管理
  /sso/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 登录
      parameters:
      - description: 客户端标识
        in: query
        name: domain
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 用户邮箱
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/static.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/static.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - Sso入口
  /sso/logout:
    post:
      description: 退出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - Sso入口
  /svc/session:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 客户端回调确认接口，更新session状态为已登录
      parameters:
      - description: 客户端域名
        in: formData
        name: domain
        required: true
        type: string
      - description: 签名
        in: formData
        name: sign
        required: true
        type: string
      - description: 时间戳
        in: formData
        name: timestamp
        required: true
        type: string
      - description: 登录token
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - Svc接口
  /svc/userinfo:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 客户端业务代码执行之前，调用该接口获取用户信息
      parameters:
      - description: 客户端域名
        in: formData
        name: domain
        required: true
        type: string
      - description: 签名
        in: formData
        name: sign
        required: true
        type: string
      - description: 时间戳
        in: formData
        name: timestamp
        required: true
        type: string
      - description: 登录token
        in: formData
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - Svc接口
swagger: "2.0"
